site_name: dwdown Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Data Module:
      - MappingStore: data/MappingStore.md
  - Download Module:
      - ForecastDownloader: download/ForecastDownloader.md
      - OSDownloader: download/OSDownloader.md
      - MosmixDownloader: download/MosmixDownloader.md
      - HistoricalDownloader: download/HistoricalDownloader.md
  - Notify Module:
      - Notifier: notify/Notifier.md
  - Processing Module:
      - DataMerger: processing/DataMerger.md
      - GribFileManager: processing/GribFileManager.md
  - Upload Module:
      - OSUploader: upload/OSUploader.md
  - Utils Module:
      - DataFrameOperator: utils/DataFrameOperator.md
      - DateTimeUtils: utils/DateTimeUtils.md
      - FileHandler: utils/FileHandler.md
      - LogHandler: utils/LogHandler.md
      - NetworkHandlers: utils/NetworkHandlers.md
      - OSHandler: utils/OSHandler.md
      - Utilities: utils/Utilities.md

markdown_extensions:
  - attr_list
  - md_in_html
